services:
  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=expense
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    networks:
      - myday-user
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: .
    container_name: myday-user-backend
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    networks:
      - myday-user
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/expense
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sankadilshan9686@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 82:80
volumes:
  db-data:
networks:
  myday-user: